# Generated by Django 4.0.4 on 2022-05-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_post_imagem_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.CharField(max_length=2000),
        ),
    ]
