# Generated by Django 4.0.4 on 2022-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_pessoa_projetos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='imagem',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
