# Generated by Django 4.0.4 on 2022-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_formacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacao',
            name='link_cadeira',
            field=models.URLField(blank=True),
        ),
    ]
