# Generated by Django 4.0.4 on 2022-05-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_projetos_participantes_projetos_participantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_cadeira', models.CharField(max_length=100)),
                ('semestre', models.IntegerField(default=1)),
                ('ects', models.IntegerField(default=0)),
                ('avaliacao', models.CharField(blank=True, max_length=100)),
                ('link_cadeira', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='ects',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='link_cadeira',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='nome_da_cadeira',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='semestre',
        ),
        migrations.AddField(
            model_name='formacao',
            name='cadeiras',
            field=models.ManyToManyField(to='portfolio.cadeiras'),
        ),
    ]
