# Generated by Django 4.0.4 on 2022-05-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_cadeiras_remove_formacao_avaliacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=100)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
                ('link_noticia', models.URLField(blank=True)),
            ],
        ),
    ]
