# Generated by Django 4.0.4 on 2022-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_noticias_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='descricao',
            field=models.CharField(max_length=400),
        ),
    ]
