# Generated by Django 4.0.4 on 2022-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_noticias_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('acronimo', models.CharField(max_length=20)),
                ('ano_criacao', models.IntegerField(default=0)),
                ('criador', models.CharField(max_length=100)),
                ('logotipo', models.ImageField(null=True, upload_to='media/')),
                ('link_oficial', models.URLField(blank=True)),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
    ]
